// AUTO-GENERATED BY scripts/sync-font-imports.js
import { Bodoni_Moda } from 'next/font/google';
import { Sans } from 'next/font/google';
import { Manrope } from 'next/font/google';
import { Retro } from 'next/font/google';
import { Courier_New } from 'next/font/google';
import { Handwriting } from 'next/font/google';
import { Rock_Salt } from 'next/font/google';
import { Playwrite_AU_NSW } from 'next/font/google';
import { Combo } from 'next/font/google';

export const bodoni_moda = Bodoni_Moda({ subsets: ['latin'], weight: ['400'], variable: '--font-bodoni_moda', display: 'swap' });
export const sans = Sans({ subsets: ['latin'], weight: ['400'], variable: '--font-sans', display: 'swap' });
export const manrope = Manrope({ subsets: ['latin'], weight: ['400'], variable: '--font-manrope', display: 'swap' });
export const retro = Retro({ subsets: ['latin'], weight: ['400'], variable: '--font-retro', display: 'swap' });
export const courier_new = Courier_New({ subsets: ['latin'], weight: ['400'], variable: '--font-courier_new', display: 'swap' });
export const handwriting = Handwriting({ subsets: ['latin'], weight: ['400'], variable: '--font-handwriting', display: 'swap' });
export const rock_salt = Rock_Salt({ subsets: ['latin'], weight: ['400'], variable: '--font-rock_salt', display: 'swap' });
export const playwrite_au_nsw = Playwrite_AU_NSW({ subsets: ['latin'], weight: ['400'], variable: '--font-playwrite_au_nsw', display: 'swap' });
export const combo = Combo({ subsets: ['latin'], weight: ['400'], variable: '--font-combo', display: 'swap' });
