import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Bodoni_Moda } from 'next/font/google';
import { Manrope } from 'next/font/google';
import "./globals.css";
import ThemeToggle from '../components/ThemeToggle';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bodoni = Bodoni_Moda({
  subsets: ['latin'],
  weight: ['400', '700'], // Regular and Bold
  variable: '--font-bodoni',
});

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Regular, Medium, Bold
  variable: '--font-manrope',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${bodoni.variable} ${manrope.variable}`}> 
      <body className="font-sans bg-background-light text-foreground-light dark:bg-background-dark dark:text-foreground-dark transition-colors duration-300">
        <header className="w-full flex justify-between items-center px-8 py-6">
          <div className="text-2xl font-light tracking-wide">Hesam Andalib</div>
          <nav className="flex gap-8 items-center">
            <a href="#projects" className="text-accent-light dark:text-accent-dark hover:underline">Projects</a>
            <a href="#about" className="text-accent-light dark:text-accent-dark hover:underline">About Me</a>
            <ThemeToggle />
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
